package com.example.springbackendtemplate1.commons.model.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;

/**
 * Abstract base class for all JPA entities in the application.
 *
 * <p>Every persistent entity must extend this class. It is intentionally
 * focused on a single responsibility: providing the common persistent state
 * that every entity in the system shares. That state covers four concerns:
 *
 * <ol>
 *   <li><b>Primary key</b> – auto-generated surrogate {@code Long} identity.</li>
 *   <li><b>Audit fields</b> – who created / last modified the record and when,
 *       populated automatically by Spring Data's {@link AuditingEntityListener}.</li>
 *   <li><b>Soft-delete fields</b> – {@code isDeleted}, {@code deletedBy}, and
 *       {@code deletedAt} allow logical deletion without removing rows from the
 *       database. {@code isActive} can be toggled independently to suspend a
 *       record without deleting it.</li>
 *   <li><b>Optimistic locking</b> – a {@code @Version} counter prevents
 *       lost-update anomalies in concurrent write scenarios.</li>
 * </ol>
 *
 * <p>Bidirectional relationship management is intentionally <em>not</em> handled
 * here. Use the static helpers in {@link EntityRelationshipHelper} from within
 * concrete entity methods instead.
 *
 * <p><b>Important:</b> this class must not contain any business-specific logic.
 * Domain behaviour belongs in the concrete entity or a dedicated domain service.
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
public abstract class AuditableEntity {

    // -------------------------------------------------------------------------
    // Primary key
    // -------------------------------------------------------------------------

    /**
     * Surrogate primary key, generated by the database identity column.
     * The value is assigned on first INSERT and must never change afterward,
     * hence {@code updatable = false}.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(updatable = false)
    private Long id;

    // -------------------------------------------------------------------------
    // Audit fields
    // -------------------------------------------------------------------------

    /**
     * ID of the user (or system principal) that created this record.
     * Populated automatically by Spring Data auditing on INSERT.
     * Immutable after creation ({@code updatable = false}).
     */
    @CreatedBy
    @Column(updatable = false)
    private Long createdBy;

    /**
     * Timestamp of when this record was first persisted.
     * Populated automatically by Spring Data auditing on INSERT.
     * Immutable after creation ({@code updatable = false, nullable = false}).
     */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * ID of the user (or system principal) that last modified this record.
     * Populated automatically by Spring Data auditing on every UPDATE.
     * Falls back to {@code createdBy} in {@link #onUpdate()} when the auditing
     * infrastructure cannot resolve a current principal (e.g. background jobs).
     */
    @LastModifiedBy
    private Long updatedBy;

    /**
     * Timestamp of the most recent modification to this record.
     * Populated automatically by Spring Data auditing on every UPDATE.
     */
    @LastModifiedDate
    private Instant updatedAt;

    // -------------------------------------------------------------------------
    // Optimistic locking
    // -------------------------------------------------------------------------

    /**
     * Optimistic-locking version counter managed exclusively by JPA.
     * Incremented on every UPDATE; a stale-read conflict throws
     * {@link jakarta.persistence.OptimisticLockException}, preventing
     * lost-update anomalies in concurrent write scenarios.
     */
    @Version
    private Long version;

    // -------------------------------------------------------------------------
    // Soft-delete fields
    // -------------------------------------------------------------------------

    /**
     * Whether this record is currently active.
     * Defaults to {@code true} on creation (see {@link #onCreate()}).
     * Can be set to {@code false} to suspend a record without deleting it —
     * useful for temporarily disabling users, products, etc.
     */
    @Column(nullable = false)
    private Boolean isActive = true;

    /**
     * Soft-delete flag. When {@code true} the record is considered logically
     * deleted and must be excluded from normal query results.
     * Defaults to {@code false} on creation (see {@link #onCreate()}).
     * Use repository-level {@code @Where} or Specification filters to enforce
     * this invariant automatically.
     */
    @Column(nullable = false)
    private Boolean isDeleted = false;

    /**
     * ID of the user (or system principal) that soft-deleted this record.
     * Null until a delete operation is performed.
     */
    private Long deletedBy;

    /**
     * Timestamp of when this record was soft-deleted.
     * Null until a delete operation is performed.
     */
    private Instant deletedAt;

    // -------------------------------------------------------------------------
    // JPA lifecycle callbacks
    // -------------------------------------------------------------------------

    /**
     * Executed by JPA immediately before the first INSERT.
     *
     * <ul>
     *   <li>Falls back to system user ({@code 1L}) when the auditing
     *       infrastructure has not populated {@code createdBy} — this can happen
     *       in data-migration scripts or tests that run without a security
     *       context.</li>
     *   <li>Mirrors {@code createdBy} into {@code updatedBy} when no modifier
     *       has been set explicitly, keeping both audit columns consistent from
     *       the very first row version.</li>
     *   <li>Explicitly resets {@code isActive} and {@code isDeleted} to their
     *       safe defaults, guarding against accidental field mutation before
     *       persist is called.</li>
     * </ul>
     */
    @PrePersist
    protected void onCreate() {
        if (createdBy == null) {
            createdBy = 1L;
        }

        if (updatedBy == null) {
            updatedBy = createdBy;
        }

        isActive = true;
        isDeleted = false;
    }

    /**
     * Executed by JPA immediately before every UPDATE.
     *
     * <p>Falls back to {@code createdBy} when the auditing infrastructure has
     * not populated {@code updatedBy} — same reasoning as in {@link #onCreate()}.
     */
    @PreUpdate
    protected void onUpdate() {
        if (updatedBy == null) {
            updatedBy = createdBy;
        }
    }
}